apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      containers:
      - name: kafdrop
        image: thomsch98/kafdrop
        env:
        - name: LISTEN
          value: "9000"
        - name: ZK_HOSTS
          value: "{{.Services.KafkaZookeeper.Endpoint}}"
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: kafdrop
spec:
  ports:
  - port: 9000
  selector:
    app: kafdrop
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kafdrop
  labels:
    app.kubernetes.io/name: kafdrop
spec:
  rules:
  - host: kafdrop-woodkraft.ntnxdomain.com
    http:
      paths:
      - path: /
        backend:
          serviceName: kafdrop
          servicePort: 9000
