kind: Deployment
apiVersion: apps/v1
metadata:
  name: cat-dog
  labels:
    app: cat-dog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cat-dog 
  template:
    metadata:
      labels:
        app: cat-dog
    spec:
      containers:
      - name: app-container
        image: <image path>
        imagePullPolicy: Always
        command: ["/usr/local/bin/python", "animal.py"]
