namespaceOverride: "kubeflow-monitoring"

nodeExporter:
  enabled: false
kubeStateMetrics:
  enabled: false

prometheusSpec:
  serviceMonitorNamespaceSelector:
    matchLabels:
      katib-metricscollector-injection: enabled
  podMonitorNamespaceSelector:
    matchLabels:
      katib-metricscollector-injection: enabled

grafana:
  namespaceOverride: "kubeflow-monitoring"

#prometheusOperator:
#  admissionWebhooks:
#    enabled: true
