namespaceOverride: "kubeflow-monitoring"

nodeExporter:
  enabled: false

prometheusSpec:
  serviceMonitorNamespaceSelector:
    matchLabels:
      katib-metricscollector-injection: enabled
  podMonitorNamespaceSelector:
    matchLabels:
      katib-metricscollector-injection: enabled
