namespaceOverride: "kubeflow-monitoring"

nodeExporter:
  enabled: false
kubeStateMetrics:
  enabled: false

prometheusSpec:
#  serviceMonitorNamespaceSelector:
#    matchExpressions:
#      - key: name
#        operator: In
#        values:
#          - knative-eventing
#          - knative-serving
#          - kubeflow
#      - key:
#    matchLabels:
#      katib-metricscollector-injection: enabled
#  podMonitorNamespaceSelector:
#    matchLabels:
#      katib-metricscollector-injection: enabled

grafana:
  namespaceOverride: "kubeflow-monitoring"
