apiVersion: apps/v1
kind: Deployment
metadata:
  name: loader
spec:
  selector:
    matchLabels:
      app: loader
  replicas: 1
  template:
    metadata:
      labels:
        app: loader
    spec:
      containers:
      - name: loader 
        image: xiiot/ecomm-loader:v4
        env:
        - name: WP_HOST
          value: "https://ingress-nginx.project-ingress"
        - name: USER
          value: "10"
        - name: API_KEY
          value: "<api key>"
        - name: API_SECRET
          value: "<api secret>"
        - name: WAIT_TIME_LRANGE
          value: "10"
        - name: WAIT_TIME_RRANGE
          value: "300"
