---
# Source: debezium-connect/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: debezium-connect
  labels:
    app: debezium-connect
spec:
  type: ClusterIP
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
    name: connect
  selector:
    app: debezium-connect

---
# Source: debezium-connect/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium-connect
  labels:
    app: debezium-connect
    version : "0.1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium-connect
  template:
    metadata:
      labels:
        app: debezium-connect
    spec:
      containers:
      - name: debezium-connect
        image: "debezium/connect:1.0"
        imagePullPolicy: IfNotPresent
        env:
        - name: GROUP_ID
          value: "1"
        - name: CONFIG_STORAGE_TOPIC
          value: my_connect_configs
        - name: OFFSET_STORAGE_TOPIC
          value: my_connect_offsets
        - name: BOOTSTRAP_SERVERS
          value: "{{.Services.Kafka.Endpoint}}"
        - name: HOST_NAME
          value: "0.0.0.0"
        ports:
        - containerPort: 8083
