apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-service
  labels:
    app: recommendation-service
    version: v1
spec:
  selector:
    matchLabels:
      app: recommendation-service
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: recommendation-service
        version: v1
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      initContainers:
      - name: init-recommendation-service
        image: xiiot/ecomm-recommendation-svc:v8
        command: ['sh', '/debezium-setup.sh']
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
        ports:
        - name: http
          containerPort: 80
      - name: recommendation-service
        image: xiiot/ecomm-recommendation-svc:v8
        env:
        - name: KAFKA_BROKER
          value: "{{.Services.Kafka.Endpoint}}"
        - name: COLOR 
          value: "b"
        - name: VERSION_STRING
          value: "V1"
        - name: MOUNT_PATH
          value: "/www"
        volumeMounts:
        - name: shared-data
          mountPath: /www
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  labels:
    app: recommendation-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: recommendation-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    server {
        listen       8081;
        server_name localhost;
        proxy_http_version 1.1;
        location / {
          proxy_pass   http://recommendation-service;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-service-lb
  labels:
    app: recommendation-service-lb
spec:
  selector:
    matchLabels:
      app: recommendation-service-lb
  replicas: 1
  template:
    metadata:
      labels:
        app: recommendation-service-lb
    spec:
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/nginx.conf
          name: nginx-conf
          subPath: nginx.conf
        ports:
        - name: http
          containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-service-lb
  labels:
    app: recommendation-service-lb
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: recommendation-service-lb
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: recommendation-service
  labels:
    app: recommendation-service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: woodkraft.ntnxdomain.com
      http:
        paths:
        - path: /recommendation-service(/|$)(.*)
          backend:
            serviceName: recommendation-service-lb
            servicePort: 8081
